pipeline {
  agent any

  parameters {
    choice(name: 'ENV', choices: ['dev'], description: 'Target environment')
    string(name: 'IMAGE_TAG', defaultValue: 'latest', description: 'Docker image tag')
    booleanParam(name: 'DEPLOY_MONITORING', defaultValue: false, description: 'Deploy monitoring stack')
  }

  environment {
    APP_NAME = "stateless-app"
    ENV_FILE = "configs/${params.ENV}.env"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Load Env') {
      steps {
        script {
          def props = readProperties file: env.ENV_FILE
          env.AWS_REGION = props['AWS_REGION']
          env.CLUSTER_NAME = props['CLUSTER_NAME']
          env.AWS_ACCOUNT_ID = props['AWS_ACCOUNT_ID']
          env.ECR_REPO_STATELESS = props['ECR_REPO_STATELESS']
          env.K8S_NAMESPACE = props['K8S_NAMESPACE']
          env.MONITORING_NAMESPACE = props['MONITORING_NAMESPACE']
        }
      }
    }

    stage('Build Docker Image') {
      steps {
        sh """
          docker build -t ${APP_NAME}:${params.IMAGE_TAG} ./apps/statelessapp
        """
      }
    }

    stage('Login to ECR') {
      steps {
        sh """
          aws ecr get-login-password --region ${AWS_REGION} | \
          docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
        """
      }
    }

    stage('Push Image to ECR') {
      steps {
        sh """
          IMAGE_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_STATELESS}:${params.IMAGE_TAG}
          docker tag ${APP_NAME}:${params.IMAGE_TAG} $IMAGE_URI
          docker push $IMAGE_URI
        """
      }
    }

    //stage('Deploy App') {
    //  steps {
     //   sh """
     //     chmod +x scripts/deploy-stateless.sh
     //     ./scripts/deploy-stateless.sh ${ENV_FILE} ${params.IMAGE_TAG}
       // """
    //  }
   // }
    stage('Deploy Stateful App via Helm') {
      when {
         expression { return env.DEPLOY_STATEFUL?.toBoolean() == true }
       }
      steps {
         script {
             sh """
               aws eks update-kubeconfig \
                 --region ${AWS_REGION} \
                 --name ${EKS_CLUSTER_NAME}
 
               kubectl get ns ${APP_NAMESPACE} >/dev/null 2>&1 || kubectl create ns ${APP_NAMESPACE}
 
               helm upgrade --install ${STATEFUL_RELEASE_NAME} ./helm/stateful-app \
                 -n ${APP_NAMESPACE} \
                 --set image.repository=${STATEFUL_ECR_REPO} \
                 --set image.tag=${IMAGE_TAG} \
                 --set persistence.enabled=true
             """
         }
       }
     }

    stage('Deploy Monitoring') {
       when {
         expression { return params.DEPLOY_MONITORING == true }
       }
       steps {
         script {
           // Update kubeconfig to make sure kubectl can talk to the target EKS cluster
           sh "aws eks update-kubeconfig --region ${env.AWS_REGION} --name ${env.CLUSTER_NAME}"

           // Check if Prometheus or Grafana deployments exist in the monitoring namespace
           // 'returnStatus: true' prevents the pipeline from failing if grep returns nothing (exit code 1)
           def monitoringExists = sh(
             script: "kubectl get deployments -n ${env.MONITORING_NAMESPACE} 2>/dev/null | grep -E 'prometheus|grafana'",
             returnStatus: true
           )

           // If grep finds them, returnStatus is 0. If it's 0, we skip deployment.
           if (monitoringExists == 0) {
             echo "Prometheus/Grafana already detected in namespace '${env.MONITORING_NAMESPACE}'. Skipping installation."
           } else {
             echo "Monitoring stack not found. Proceeding with deployment..."
             sh """
               chmod +x scripts/deploy-monitoring.sh
               ./scripts/deploy-monitoring.sh ${ENV_FILE}
             """
        }
       }
      }
    }
  }
}
