replicaCount: 1

image:
  repository: 045861053549.dkr.ecr.ap-south-1.amazonaws.com/eks-cicd-poc/dev/stateless-app
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: stateless-app-sa

service:
  type: ClusterIP
  port: 5000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

app:
  port: 5000
