apiVersion: v1
kind: Service
metadata:
  name: stateless-app
  namespace: {{ .Release.Namespace }}
  labels:
    app: stateless-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: stateless-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}
      protocol: TCP
      name: http
