apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stateful-app-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
{{- range .Values.storage.accessModes }}
    - {{ . }}
{{- end }}
  storageClassName: {{ .Values.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
