apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-efs-pvc
  namespace: apps

spec:
  accessModes:
    - ReadWriteMany

  storageClassName: efs-sc

  resources:
    requests:
      storage: 5Gi
